"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ThesisEngine = void 0;
const openai_1 = __importDefault(require("openai"));
class ThesisEngine {
    constructor() {
        this.openai = new openai_1.default({
            apiKey: process.env.OPENAI_API_KEY
        });
    }
    async buildThesis(input) {
        var _a, _b, _c;
        const prompt = `
You are the strategic analysis layer of an institutional trading system.

Your role is to interpret signals generated by deterministic engines.

IMPORTANT RULES

You must ONLY use the information provided below.
You must NOT invent or assume:

- ETF flows
- options positioning
- bond yields
- stablecoin demand
- liquidity injections
- derivatives positioning
- order book dynamics

If the system did not provide a signal, you must not reference it.

Your analysis must rely ONLY on:

• technical structure
• macro regime
• geopolitical events
• the provided trade levels

System Inputs

Asset: ${input.asset}
Direction: ${input.direction}
Confidence: ${input.confidence}%

Technical
Trend: ${input.technical.trend}
Momentum: ${input.technical.momentum}
Structure: ${input.technical.structure}

Macro Regime
${input.macroRegime}

Relevant Events
${input.events.join("\n")}

Trade Plan
Entry: ${input.entry} - ${input.entryHigh}
Stop Loss: ${input.stopLoss}
Targets: ${(_a = input.targets) === null || _a === void 0 ? void 0 : _a.join(", ")}

Write the explanation using EXACTLY this structure:

Strategic View:
(2–3 sentences explaining the trade using only the provided signals)

Dominant Driver:
(the main factor supporting the trade)

Key Risk:
(the biggest risk given the macro or geopolitical environment)

Invalidation:
(the condition under which the trade fails)
`;
        const response = await this.openai.chat.completions.create({
            model: process.env.OPENAI_MODEL || "gpt-5",
            messages: [
                {
                    role: "system",
                    content: "You are the strategic review layer of a quantitative macro trading system."
                },
                {
                    role: "user",
                    content: prompt
                }
            ]
        });
        const narrative = ((_b = response.choices[0].message) === null || _b === void 0 ? void 0 : _b.content) || "";
        const riskMatch = narrative.match(/Key Risk:\s*([\s\S]*?)\n\nInvalidation:/);
        const risk = riskMatch ? riskMatch[1].trim() : "";
        return {
            asset: input.asset,
            direction: input.direction,
            confidence: input.confidence,
            narrative,
            risk,
            tradePlan: {
                entry: `${input.entry} - ${input.entryHigh}`,
                stopLoss: `${input.stopLoss}`,
                targets: ((_c = input.targets) === null || _c === void 0 ? void 0 : _c.map(t => String(t))) || []
            }
        };
    }
}
exports.ThesisEngine = ThesisEngine;
