import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

export async function aiReviewEngine(input: any) {

  const systemPrompt = `
You are the Strategic Review Layer for an institutional macro trading system.

Your job is to review a preliminary trade generated by deterministic engines.

Rules:
- You MUST NOT modify entry, stop loss, or targets.
- You may only:
  • confirm the trade
  • slightly downgrade confidence
  • veto ONLY in extreme conditions

- You MUST NOT change BUY or SELL to NO_TRADE unless:
  • data is missing or invalid
  • or extreme contradiction exists across ALL signals

- If a dominant driver exists (trend, liquidity, or structure), you MUST keep BUY or SELL.

- Do NOT default to NO_TRADE.

Return ONLY JSON in this format:

{
 "action": "CONFIRM | DOWNGRADE | VETO",
 "finalDirection": "BUY | SELL | NO_TRADE",
 "finalConfidence": number,
 "rationale": "short explanation"
}
`;

  const userPrompt = JSON.stringify(input, null, 2);

  const completion = await client.chat.completions.create({
    model: "gpt-4.1",
    temperature: 0.2,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ]
  });

  const text = completion.choices[0].message?.content || "{}";

  try {
    return JSON.parse(text);
  }
catch {
  return {
    action: "CONFIRM",
    finalDirection: input.direction,
    finalConfidence: input.confidence,
    rationale: "Review fallback → keeping AI decision"
  };
}
}