import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

export async function aiReviewEngine(input: any) {

  const systemPrompt = `
You are the Strategic Review Layer for an institutional macro trading system.

Your job is to review a preliminary trade generated by deterministic engines.

Rules:
- You MUST NOT modify entry, stop loss, or targets.
- You may only:
  • confirm the trade
  • downgrade confidence
  • change BUY or SELL to NO_TRADE
  • veto the trade entirely
- Be conservative. If signals conflict or risk is high → prefer NO_TRADE.

Return ONLY JSON in this format:

{
 "action": "CONFIRM | DOWNGRADE | VETO",
 "finalDirection": "BUY | SELL | NO_TRADE",
 "finalConfidence": number,
 "rationale": "short explanation"
}
`;

  const userPrompt = JSON.stringify(input, null, 2);

  const completion = await client.chat.completions.create({
    model: "gpt-4.1",
    temperature: 0.2,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ]
  });

  const text = completion.choices[0].message?.content || "{}";

  try {
    return JSON.parse(text);
  } catch {
    return {
      action: "VETO",
      finalDirection: "NO_TRADE",
      finalConfidence: 0,
      rationale: "AI review parsing failed"
    };
  }
}